package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolesResources generated by hbm2java
 */
@Entity
@Table(name = "ROLES_RESOURCES")
public class RolesResources implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RolesResourcesId id;
	private Roles roles;

	public RolesResources() {
	}

	public RolesResources(RolesResourcesId id, Roles roles) {
		this.id = id;
		this.roles = roles;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "roleCode", column = @Column(name = "ROLE_CODE", nullable = false, length = 30)),
			@AttributeOverride(name = "productCode", column = @Column(name = "PRODUCT_CODE", nullable = false, length = 10)),
			@AttributeOverride(name = "resourceId", column = @Column(name = "RESOURCE_ID", nullable = false, precision = 22, scale = 0)) })
	public RolesResourcesId getId() {
		return this.id;
	}

	public void setId(RolesResourcesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ROLE_CODE", referencedColumnName = "ROLE_CODE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRODUCT_CODE", referencedColumnName = "PRODUCT_CODE", nullable = false, insertable = false, updatable = false) })
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
