package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersKycInfoId generated by hbm2java
 */
@Embeddable
public class UsersKycInfoId implements java.io.Serializable {

	private BigDecimal kycId;
	private BigDecimal accountId;

	public UsersKycInfoId() {
	}

	public UsersKycInfoId(BigDecimal kycId, BigDecimal accountId) {
		this.kycId = kycId;
		this.accountId = accountId;
	}

	@Column(name = "KYC_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getKycId() {
		return this.kycId;
	}

	public void setKycId(BigDecimal kycId) {
		this.kycId = kycId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAccountId() {
		return this.accountId;
	}

	public void setAccountId(BigDecimal accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersKycInfoId))
			return false;
		UsersKycInfoId castOther = (UsersKycInfoId) other;

		return ((this.getKycId() == castOther.getKycId()) || (this.getKycId() != null
				&& castOther.getKycId() != null && this.getKycId().equals(
				castOther.getKycId())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this
						.getAccountId() != null
						&& castOther.getAccountId() != null && this
						.getAccountId().equals(castOther.getAccountId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKycId() == null ? 0 : this.getKycId().hashCode());
		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		return result;
	}

}
