package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGroupRoles generated by hbm2java
 */
@Entity
@Table(name = "USERS_GROUP_ROLES")
public class UsersGroupRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsersGroupRolesId id;
	private Users users;
	private GroupRoles groupRoles;

	public UsersGroupRoles() {
	}

	public UsersGroupRoles(UsersGroupRolesId id, Users users,
			GroupRoles groupRoles) {
		this.id = id;
		this.users = users;
		this.groupRoles = groupRoles;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "ACCOUNT_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "groupRoleCode", column = @Column(name = "GROUP_ROLE_CODE", nullable = false, length = 30)) })
	public UsersGroupRolesId getId() {
		return this.id;
	}

	public void setId(UsersGroupRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ROLE_CODE", nullable = false, insertable = false, updatable = false)
	public GroupRoles getGroupRoles() {
		return this.groupRoles;
	}

	public void setGroupRoles(GroupRoles groupRoles) {
		this.groupRoles = groupRoles;
	}

}
