package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
@NamedQuery(name="Users.findAll",query="SELECT U FROM Users U")
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal accountId;
	private String age;
	private String religion;
	private String userId;
	private String msisdn;
	private String nodeCode;
	private String parentAccountId;
	private String userType;
	private String shippingAddress;
	private String shippingCity;
	private String shippingState;
	private String shippingZipCode;
	private String homeAddress;
	private String homeCity;
	private String homeState;
	private String homeZipCode;
	private String address1;
	private String address1City;
	private String address1State;
	private String address1ZipCode;
	private String primaryPhoneNbr;
	private String secondaryPhoneNbr;
	private String secondaryPhoneNbr2;
	private String secondaryPhoneNbr3;
	private String secondaryPhoneNbr4;
	private String authenticationType;
	private String firstName;
	private String namePrefix;
	private String middleName;
	private String lastName;
	private String status;
	private String allowedIp;
	private String allowedDays;
	private String fromTime;
	private String toTime;
	private Date dob;
	private Date lastLoginOn;
	private String email;
	private String level1ApprovedBy;
	private Date level1ApprovedOn;
	private String level2ApprovedBy;
	private Date level2ApprovedOn;
	private String batchId;
	private String remarks;
	private String modifyApprovedBy;
	private Date modifyApprovedOn;
	private String deleteApprovedBy;
	private Date deleteApprovedOn;
	private String prefLanguage;
	private String mnoId;
	private String col1;
	private String col2;
	private String col3;
	private String col4;
	private String col5;
	private String col6;
	private String col7;
	private String col8;
	private String col9;
	private String col10;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set<UsersKycInfo> usersKycInfos = new HashSet<UsersKycInfo>(0);
	private Set<UserAuditTrail> userAuditTrails = new HashSet<UserAuditTrail>(0);
	private UserPasswords userPasswords;
	private Set<UsersGroupRoles> usersGroupRoleses = new HashSet<UsersGroupRoles>(0);
	private Set<UserLogonAudit> userLogonAudits = new HashSet<UserLogonAudit>(0);
	private Set<UserThresholds> userThresholdses = new HashSet<UserThresholds>(0);

	public Users() {
	}

	public Users(BigDecimal accountId, String nodeCode, Date createdOn,
			String createdBy) {
		this.accountId = accountId;
		this.nodeCode = nodeCode;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}


	@Id
	@Column(name = "ACCOUNT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAccountId() {
		return this.accountId;
	}

	public void setAccountId(BigDecimal accountId) {
		this.accountId = accountId;
	}

	@Column(name = "AGE", length = 30)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "RELIGION", length = 30)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "USER_ID", length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "MSISDN", length = 30)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "NODE_CODE", nullable = false, length = 30)
	public String getNodeCode() {
		return this.nodeCode;
	}

	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	@Column(name = "PARENT_ACCOUNT_ID", length = 30)
	public String getParentAccountId() {
		return this.parentAccountId;
	}

	public void setParentAccountId(String parentAccountId) {
		this.parentAccountId = parentAccountId;
	}

	@Column(name = "USER_TYPE", length = 30)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "SHIPPING_ADDRESS", length = 30)
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	@Column(name = "SHIPPING_CITY", length = 30)
	public String getShippingCity() {
		return this.shippingCity;
	}

	public void setShippingCity(String shippingCity) {
		this.shippingCity = shippingCity;
	}

	@Column(name = "SHIPPING_STATE", length = 30)
	public String getShippingState() {
		return this.shippingState;
	}

	public void setShippingState(String shippingState) {
		this.shippingState = shippingState;
	}

	@Column(name = "SHIPPING_ZIP_CODE", length = 20)
	public String getShippingZipCode() {
		return this.shippingZipCode;
	}

	public void setShippingZipCode(String shippingZipCode) {
		this.shippingZipCode = shippingZipCode;
	}

	@Column(name = "HOME_ADDRESS", length = 100)
	public String getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "HOME_CITY", length = 30)
	public String getHomeCity() {
		return this.homeCity;
	}

	public void setHomeCity(String homeCity) {
		this.homeCity = homeCity;
	}

	@Column(name = "HOME_STATE", length = 30)
	public String getHomeState() {
		return this.homeState;
	}

	public void setHomeState(String homeState) {
		this.homeState = homeState;
	}

	@Column(name = "HOME_ZIP_CODE", length = 20)
	public String getHomeZipCode() {
		return this.homeZipCode;
	}

	public void setHomeZipCode(String homeZipCode) {
		this.homeZipCode = homeZipCode;
	}

	@Column(name = "ADDRESS_1", length = 30)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS_1_CITY", length = 30)
	public String getAddress1City() {
		return this.address1City;
	}

	public void setAddress1City(String address1City) {
		this.address1City = address1City;
	}

	@Column(name = "ADDRESS_1_STATE", length = 30)
	public String getAddress1State() {
		return this.address1State;
	}

	public void setAddress1State(String address1State) {
		this.address1State = address1State;
	}

	@Column(name = "ADDRESS_1_ZIP_CODE", length = 20)
	public String getAddress1ZipCode() {
		return this.address1ZipCode;
	}

	public void setAddress1ZipCode(String address1ZipCode) {
		this.address1ZipCode = address1ZipCode;
	}

	@Column(name = "PRIMARY_PHONE_NBR", length = 30)
	public String getPrimaryPhoneNbr() {
		return this.primaryPhoneNbr;
	}

	public void setPrimaryPhoneNbr(String primaryPhoneNbr) {
		this.primaryPhoneNbr = primaryPhoneNbr;
	}

	@Column(name = "SECONDARY_PHONE_NBR", length = 30)
	public String getSecondaryPhoneNbr() {
		return this.secondaryPhoneNbr;
	}

	public void setSecondaryPhoneNbr(String secondaryPhoneNbr) {
		this.secondaryPhoneNbr = secondaryPhoneNbr;
	}

	@Column(name = "SECONDARY_PHONE_NBR2", length = 30)
	public String getSecondaryPhoneNbr2() {
		return this.secondaryPhoneNbr2;
	}

	public void setSecondaryPhoneNbr2(String secondaryPhoneNbr2) {
		this.secondaryPhoneNbr2 = secondaryPhoneNbr2;
	}

	@Column(name = "SECONDARY_PHONE_NBR3", length = 30)
	public String getSecondaryPhoneNbr3() {
		return this.secondaryPhoneNbr3;
	}

	public void setSecondaryPhoneNbr3(String secondaryPhoneNbr3) {
		this.secondaryPhoneNbr3 = secondaryPhoneNbr3;
	}

	@Column(name = "SECONDARY_PHONE_NBR4", length = 30)
	public String getSecondaryPhoneNbr4() {
		return this.secondaryPhoneNbr4;
	}

	public void setSecondaryPhoneNbr4(String secondaryPhoneNbr4) {
		this.secondaryPhoneNbr4 = secondaryPhoneNbr4;
	}

	@Column(name = "AUTHENTICATION_TYPE", length = 30)
	public String getAuthenticationType() {
		return this.authenticationType;
	}

	public void setAuthenticationType(String authenticationType) {
		this.authenticationType = authenticationType;
	}

	@Column(name = "FIRST_NAME", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "NAME_PREFIX", length = 30)
	public String getNamePrefix() {
		return this.namePrefix;
	}

	public void setNamePrefix(String namePrefix) {
		this.namePrefix = namePrefix;
	}

	@Column(name = "MIDDLE_NAME", length = 30)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "STATUS", length = 30)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ALLOWED_IP", length = 150)
	public String getAllowedIp() {
		return this.allowedIp;
	}

	public void setAllowedIp(String allowedIp) {
		this.allowedIp = allowedIp;
	}

	@Column(name = "ALLOWED_DAYS", length = 15)
	public String getAllowedDays() {
		return this.allowedDays;
	}

	public void setAllowedDays(String allowedDays) {
		this.allowedDays = allowedDays;
	}

	@Column(name = "FROM_TIME", length = 10)
	public String getFromTime() {
		return this.fromTime;
	}

	public void setFromTime(String fromTime) {
		this.fromTime = fromTime;
	}

	@Column(name = "TO_TIME", length = 10)
	public String getToTime() {
		return this.toTime;
	}

	public void setToTime(String toTime) {
		this.toTime = toTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 7)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_LOGIN_ON", length = 7)
	public Date getLastLoginOn() {
		return this.lastLoginOn;
	}

	public void setLastLoginOn(Date lastLoginOn) {
		this.lastLoginOn = lastLoginOn;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "LEVEL1_APPROVED_BY", length = 30)
	public String getLevel1ApprovedBy() {
		return this.level1ApprovedBy;
	}

	public void setLevel1ApprovedBy(String level1ApprovedBy) {
		this.level1ApprovedBy = level1ApprovedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LEVEL1_APPROVED_ON", length = 7)
	public Date getLevel1ApprovedOn() {
		return this.level1ApprovedOn;
	}

	public void setLevel1ApprovedOn(Date level1ApprovedOn) {
		this.level1ApprovedOn = level1ApprovedOn;
	}

	@Column(name = "LEVEL2_APPROVED_BY", length = 30)
	public String getLevel2ApprovedBy() {
		return this.level2ApprovedBy;
	}

	public void setLevel2ApprovedBy(String level2ApprovedBy) {
		this.level2ApprovedBy = level2ApprovedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LEVEL2_APPROVED_ON", length = 7)
	public Date getLevel2ApprovedOn() {
		return this.level2ApprovedOn;
	}

	public void setLevel2ApprovedOn(Date level2ApprovedOn) {
		this.level2ApprovedOn = level2ApprovedOn;
	}

	@Column(name = "BATCH_ID", length = 35)
	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	@Column(name = "REMARKS", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "MODIFY_APPROVED_BY", length = 30)
	public String getModifyApprovedBy() {
		return this.modifyApprovedBy;
	}

	public void setModifyApprovedBy(String modifyApprovedBy) {
		this.modifyApprovedBy = modifyApprovedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_APPROVED_ON", length = 7)
	public Date getModifyApprovedOn() {
		return this.modifyApprovedOn;
	}

	public void setModifyApprovedOn(Date modifyApprovedOn) {
		this.modifyApprovedOn = modifyApprovedOn;
	}

	@Column(name = "DELETE_APPROVED_BY", length = 30)
	public String getDeleteApprovedBy() {
		return this.deleteApprovedBy;
	}

	public void setDeleteApprovedBy(String deleteApprovedBy) {
		this.deleteApprovedBy = deleteApprovedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELETE_APPROVED_ON", length = 7)
	public Date getDeleteApprovedOn() {
		return this.deleteApprovedOn;
	}

	public void setDeleteApprovedOn(Date deleteApprovedOn) {
		this.deleteApprovedOn = deleteApprovedOn;
	}

	@Column(name = "PREF_LANGUAGE", length = 5)
	public String getPrefLanguage() {
		return this.prefLanguage;
	}

	public void setPrefLanguage(String prefLanguage) {
		this.prefLanguage = prefLanguage;
	}

	@Column(name = "MNO_ID", length = 20)
	public String getMnoId() {
		return this.mnoId;
	}

	public void setMnoId(String mnoId) {
		this.mnoId = mnoId;
	}

	@Column(name = "COL1", length = 30)
	public String getCol1() {
		return this.col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

	@Column(name = "COL2", length = 30)
	public String getCol2() {
		return this.col2;
	}

	public void setCol2(String col2) {
		this.col2 = col2;
	}

	@Column(name = "COL3", length = 30)
	public String getCol3() {
		return this.col3;
	}

	public void setCol3(String col3) {
		this.col3 = col3;
	}

	@Column(name = "COL4", length = 30)
	public String getCol4() {
		return this.col4;
	}

	public void setCol4(String col4) {
		this.col4 = col4;
	}

	@Column(name = "COL5", length = 30)
	public String getCol5() {
		return this.col5;
	}

	public void setCol5(String col5) {
		this.col5 = col5;
	}

	@Column(name = "COL6", length = 30)
	public String getCol6() {
		return this.col6;
	}

	public void setCol6(String col6) {
		this.col6 = col6;
	}

	@Column(name = "COL7", length = 30)
	public String getCol7() {
		return this.col7;
	}

	public void setCol7(String col7) {
		this.col7 = col7;
	}

	@Column(name = "COL8", length = 30)
	public String getCol8() {
		return this.col8;
	}

	public void setCol8(String col8) {
		this.col8 = col8;
	}

	@Column(name = "COL9", length = 30)
	public String getCol9() {
		return this.col9;
	}

	public void setCol9(String col9) {
		this.col9 = col9;
	}

	@Column(name = "COL10", length = 30)
	public String getCol10() {
		return this.col10;
	}

	public void setCol10(String col10) {
		this.col10 = col10;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", nullable = false, length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_ON", length = 7)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UsersKycInfo> getUsersKycInfos() {
		return this.usersKycInfos;
	}

	public void setUsersKycInfos(Set<UsersKycInfo> usersKycInfos) {
		this.usersKycInfos = usersKycInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserAuditTrail> getUserAuditTrails() {
		return this.userAuditTrails;
	}

	public void setUserAuditTrails(Set<UserAuditTrail> userAuditTrails) {
		this.userAuditTrails = userAuditTrails;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public UserPasswords getUserPasswords() {
		return this.userPasswords;
	}

	public void setUserPasswords(UserPasswords userPasswords) {
		this.userPasswords = userPasswords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UsersGroupRoles> getUsersGroupRoleses() {
		return this.usersGroupRoleses;
	}

	public void setUsersGroupRoleses(Set<UsersGroupRoles> usersGroupRoleses) {
		this.usersGroupRoleses = usersGroupRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserLogonAudit> getUserLogonAudits() {
		return this.userLogonAudits;
	}

	public void setUserLogonAudits(Set<UserLogonAudit> userLogonAudits) {
		this.userLogonAudits = userLogonAudits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserThresholds> getUserThresholdses() {
		return this.userThresholdses;
	}

	public void setUserThresholdses(Set<UserThresholds> userThresholdses) {
		this.userThresholdses = userThresholdses;
	}

}
