package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileComplaint generated by hbm2java
 */
@Entity
@Table(name = "FILE_COMPLAINT")
public class FileComplaint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String complaintId;
	private String transactionId;
	private String compReason;
	private String nodeCode;
	private String issMastMnoId;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String status;

	public FileComplaint() {
	}

	public FileComplaint(String complaintId, Date createdOn, String createdBy) {
		this.complaintId = complaintId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public FileComplaint(String complaintId, String transactionId,
			String compReason, String nodeCode, String issMastMnoId,
			Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, String status) {
		this.complaintId = complaintId;
		this.transactionId = transactionId;
		this.compReason = compReason;
		this.nodeCode = nodeCode;
		this.issMastMnoId = issMastMnoId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.status = status;
	}

	@Id
	@Column(name = "COMPLAINT_ID", unique = true, nullable = false, length = 20)
	public String getComplaintId() {
		return this.complaintId;
	}

	public void setComplaintId(String complaintId) {
		this.complaintId = complaintId;
	}

	@Column(name = "TRANSACTION_ID", length = 30)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "COMP_REASON", length = 200)
	public String getCompReason() {
		return this.compReason;
	}

	public void setCompReason(String compReason) {
		this.compReason = compReason;
	}

	@Column(name = "NODE_CODE", length = 30)
	public String getNodeCode() {
		return this.nodeCode;
	}

	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	@Column(name = "ISS_MAST_MNO_ID", length = 30)
	public String getIssMastMnoId() {
		return this.issMastMnoId;
	}

	public void setIssMastMnoId(String issMastMnoId) {
		this.issMastMnoId = issMastMnoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", nullable = false, length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_ON", length = 7)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "STATUS", length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
