package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Languages generated by hbm2java
 */
@Entity
@Table(name = "LANGUAGES")
public class Languages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String langCode;
	private String language;

	public Languages() {
	}

	public Languages(String langCode) {
		this.langCode = langCode;
	}

	public Languages(String langCode, String language) {
		this.langCode = langCode;
		this.language = language;
	}

	@Id
	@Column(name = "LANG_CODE", unique = true, nullable = false, length = 30)
	public String getLangCode() {
		return this.langCode;
	}

	public void setLangCode(String langCode) {
		this.langCode = langCode;
	}

	@Column(name = "LANGUAGE", length = 30)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
