package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolesHierarchyId generated by hbm2java
 */
@Embeddable
public class RolesHierarchyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String roleCode;
	private String nodeCode;
	private String productCode;

	public RolesHierarchyId() {
	}

	public RolesHierarchyId(String roleCode, String nodeCode, String productCode) {
		this.roleCode = roleCode;
		this.nodeCode = nodeCode;
		this.productCode = productCode;
	}

	@Column(name = "ROLE_CODE", nullable = false, length = 30)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "NODE_CODE", nullable = false, length = 30)
	public String getNodeCode() {
		return this.nodeCode;
	}

	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	@Column(name = "PRODUCT_CODE", nullable = false, length = 10)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolesHierarchyId))
			return false;
		RolesHierarchyId castOther = (RolesHierarchyId) other;

		return ((this.getRoleCode() == castOther.getRoleCode()) || (this
				.getRoleCode() != null && castOther.getRoleCode() != null && this
				.getRoleCode().equals(castOther.getRoleCode())))
				&& ((this.getNodeCode() == castOther.getNodeCode()) || (this
						.getNodeCode() != null
						&& castOther.getNodeCode() != null && this
						.getNodeCode().equals(castOther.getNodeCode())))
				&& ((this.getProductCode() == castOther.getProductCode()) || (this
						.getProductCode() != null
						&& castOther.getProductCode() != null && this
						.getProductCode().equals(castOther.getProductCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleCode() == null ? 0 : this.getRoleCode().hashCode());
		result = 37 * result
				+ (getNodeCode() == null ? 0 : this.getNodeCode().hashCode());
		result = 37
				* result
				+ (getProductCode() == null ? 0 : this.getProductCode()
						.hashCode());
		return result;
	}

}
