package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysPreferences generated by hbm2java
 */
@Entity
@Table(name = "SYS_PREFERENCES")
public class SysPreferences implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String preferenceCode;
	private String description;
	private String valueDatatype;
	private String valueOptions;
	private String defaultValue;
	private Character modifiedAllowed;
	private Character displayAllowed;

	public SysPreferences() {
	}

	public SysPreferences(String preferenceCode) {
		this.preferenceCode = preferenceCode;
	}

	public SysPreferences(String preferenceCode, String description,
			String valueDatatype, String valueOptions, String defaultValue,
			Character modifiedAllowed, Character displayAllowed) {
		this.preferenceCode = preferenceCode;
		this.description = description;
		this.valueDatatype = valueDatatype;
		this.valueOptions = valueOptions;
		this.defaultValue = defaultValue;
		this.modifiedAllowed = modifiedAllowed;
		this.displayAllowed = displayAllowed;
	}

	@Id
	@Column(name = "PREFERENCE_CODE", unique = true, nullable = false, length = 30)
	public String getPreferenceCode() {
		return this.preferenceCode;
	}

	public void setPreferenceCode(String preferenceCode) {
		this.preferenceCode = preferenceCode;
	}

	@Column(name = "DESCRIPTION", length = 80)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "VALUE_DATATYPE", length = 20)
	public String getValueDatatype() {
		return this.valueDatatype;
	}

	public void setValueDatatype(String valueDatatype) {
		this.valueDatatype = valueDatatype;
	}

	@Column(name = "VALUE_OPTIONS", length = 10)
	public String getValueOptions() {
		return this.valueOptions;
	}

	public void setValueOptions(String valueOptions) {
		this.valueOptions = valueOptions;
	}

	@Column(name = "DEFAULT_VALUE", length = 30)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "MODIFIED_ALLOWED", length = 1)
	public Character getModifiedAllowed() {
		return this.modifiedAllowed;
	}

	public void setModifiedAllowed(Character modifiedAllowed) {
		this.modifiedAllowed = modifiedAllowed;
	}

	@Column(name = "DISPLAY_ALLOWED", length = 1)
	public Character getDisplayAllowed() {
		return this.displayAllowed;
	}

	public void setDisplayAllowed(Character displayAllowed) {
		this.displayAllowed = displayAllowed;
	}

}
