package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLogonAuditId generated by hbm2java
 */
@Embeddable
public class UserLogonAuditId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal logonAuditId;
	private BigDecimal accountId;

	public UserLogonAuditId() {
	}

	public UserLogonAuditId(BigDecimal logonAuditId, BigDecimal accountId) {
		this.logonAuditId = logonAuditId;
		this.accountId = accountId;
	}

	@Column(name = "LOGON_AUDIT_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLogonAuditId() {
		return this.logonAuditId;
	}

	public void setLogonAuditId(BigDecimal logonAuditId) {
		this.logonAuditId = logonAuditId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAccountId() {
		return this.accountId;
	}

	public void setAccountId(BigDecimal accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserLogonAuditId))
			return false;
		UserLogonAuditId castOther = (UserLogonAuditId) other;

		return ((this.getLogonAuditId() == castOther.getLogonAuditId()) || (this
				.getLogonAuditId() != null
				&& castOther.getLogonAuditId() != null && this
				.getLogonAuditId().equals(castOther.getLogonAuditId())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this
						.getAccountId() != null
						&& castOther.getAccountId() != null && this
						.getAccountId().equals(castOther.getAccountId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getLogonAuditId() == null ? 0 : this.getLogonAuditId()
						.hashCode());
		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		return result;
	}

}
