package com.mrptech.mess.model;

// Generated Feb 15, 2015 10:58:50 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserThresholdsId generated by hbm2java
 */
@Embeddable
public class UserThresholdsId implements java.io.Serializable {

	private BigDecimal thresholdId;
	private BigDecimal accountId;

	public UserThresholdsId() {
	}

	public UserThresholdsId(BigDecimal thresholdId, BigDecimal accountId) {
		this.thresholdId = thresholdId;
		this.accountId = accountId;
	}

	@Column(name = "THRESHOLD_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getThresholdId() {
		return this.thresholdId;
	}

	public void setThresholdId(BigDecimal thresholdId) {
		this.thresholdId = thresholdId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAccountId() {
		return this.accountId;
	}

	public void setAccountId(BigDecimal accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserThresholdsId))
			return false;
		UserThresholdsId castOther = (UserThresholdsId) other;

		return ((this.getThresholdId() == castOther.getThresholdId()) || (this
				.getThresholdId() != null && castOther.getThresholdId() != null && this
				.getThresholdId().equals(castOther.getThresholdId())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this
						.getAccountId() != null
						&& castOther.getAccountId() != null && this
						.getAccountId().equals(castOther.getAccountId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getThresholdId() == null ? 0 : this.getThresholdId()
						.hashCode());
		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		return result;
	}

}
